/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Radnik;
import domen.Ucinak;
import domen.VrstaPosla;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import konstante.Operacije;
import kontroler.Komunikacija;
import modeli.ModelTabeleKlijent;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;


public class KlijentskaForma extends javax.swing.JFrame {

    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Klijentska forma");
        popuniComboVrstePoslova();
        popuniComboRadnika();
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbVrstaPosla = new javax.swing.JComboBox();
        cmbRadnik = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBrojSati = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnDodajUcinak = new javax.swing.JButton();
        btnObrisiUcinak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUcinakRadnika = new javax.swing.JTable();
        btnSacuvajUcinak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vrsta posla:");

        cmbVrstaPosla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbRadnik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Radnik:");

        jLabel3.setText("Broj sati:");

        jLabel4.setText("Datum:");

        btnDodajUcinak.setText("Dodaj ucinak");
        btnDodajUcinak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajUcinakActionPerformed(evt);
            }
        });

        btnObrisiUcinak.setText("Obrisi ucinak");
        btnObrisiUcinak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiUcinakActionPerformed(evt);
            }
        });

        tblUcinakRadnika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUcinakRadnika);

        btnSacuvajUcinak.setText("Sacuvaj ucinak radnika");
        btnSacuvajUcinak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajUcinakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvajUcinak, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbVrstaPosla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbRadnik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtBrojSati, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(btnDodajUcinak, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(64, 64, 64)
                            .addComponent(btnObrisiUcinak, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbVrstaPosla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBrojSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajUcinak)
                    .addComponent(btnObrisiUcinak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSacuvajUcinak)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiUcinakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiUcinakActionPerformed
        // TODO add your handling code here:
        int red = tblUcinakRadnika.getSelectedRow();
        
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Greska");
            return;
        }else{
            
            ModelTabeleKlijent mtk = (ModelTabeleKlijent) tblUcinakRadnika.getModel();
            mtk.obrisi(red);
            
            
        }
        
        
        
    }//GEN-LAST:event_btnObrisiUcinakActionPerformed

    private void btnSacuvajUcinakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajUcinakActionPerformed
        // TODO add your handling code here:
        ModelTabeleKlijent mtk = (ModelTabeleKlijent) tblUcinakRadnika.getModel();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        
        ArrayList<Ucinak> lista = mtk.getLista();
        
        for (int i = 0; i < lista.size(); i++) {
            Ucinak u1 = lista.get(i);
            for (int j = i + 1; j < lista.size(); j++) {
                Ucinak u2 = lista.get(j);
                
                if (u1.getRadnik().getRadnikID() == u2.getRadnik().getRadnikID()
                        && u1.getVrstaPosla().getVrstaPoslaID() != u2.getVrstaPosla().getVrstaPoslaID()) {
                    JOptionPane.showMessageDialog(this, "Radnik moze raditi samo jednu vrstu posla!");
                    return;
                }
            }
        }
        
        for (int i = 0; i < lista.size(); i++) {
            Ucinak u1 = lista.get(i);
            int ukupnoSati = u1.getBrojSati();
            String dat1 = sdf.format(u1.getDatum());
            for (int j = i + 1; j < lista.size(); j++) {
                Ucinak u2 = lista.get(j);
                String dat2 = sdf.format(u2.getDatum());
                
                if (u1.getRadnik().getRadnikID() == u2.getRadnik().getRadnikID()
                        && dat1.equals(dat2)) {
                    
                    ukupnoSati += u2.getBrojSati();
                    
                }
            }
            
            if (ukupnoSati > 8) {
                JOptionPane.showMessageDialog(this, "Radnik moze raditi max 8 sati!");
                return;
            }
        }
        
        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Popunite ucinke!");
            return;
        }
        
        try {
            KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.SACUVAJ_UCINAK, lista);
            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

            if (so != null && so.getOdgovor() != null && (Boolean) so.getOdgovor()) {
                JOptionPane.showMessageDialog(this, "Uspesno sacuvano!");
            }else{
                JOptionPane.showMessageDialog(this, "Nije uspesno!");
                return;
        }
        } catch (Exception ex) {
            Logger.getLogger(KlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Greška: " + ex.getMessage());
        }
        
        
        
    }//GEN-LAST:event_btnSacuvajUcinakActionPerformed

    private void btnDodajUcinakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajUcinakActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        
        VrstaPosla vp = (VrstaPosla) cmbVrstaPosla.getSelectedItem();
        Radnik r = (Radnik) cmbRadnik.getSelectedItem();
        
        String br = txtBrojSati.getText();
        String dat = txtDatum.getText();
        
        if (br.isEmpty() || dat.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Sva polja moraju biti popunjena!");
            return;
        }
        
        for (int i = 0; i < br.length(); i++) {
            if (!Character.isDigit(br.charAt(i))) {
                JOptionPane.showMessageDialog(this,"Broj mora biti cifra!");
                return;
            }
        }
        
        Date datum = null;
        
        int brojSati = Integer.parseInt(br);
        
        try {
            datum = sdf.parse(dat);
        } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this,"Datum nije u dobrom formatu!");
                return;
        }
        
        Ucinak u = new Ucinak(-1, brojSati, datum, r, vp);
        
        ModelTabeleKlijent mtk = (ModelTabeleKlijent) tblUcinakRadnika.getModel();
        
        mtk.dodajUcinak(u);
        
        
    }//GEN-LAST:event_btnDodajUcinakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajUcinak;
    private javax.swing.JButton btnObrisiUcinak;
    private javax.swing.JButton btnSacuvajUcinak;
    private javax.swing.JComboBox cmbRadnik;
    private javax.swing.JComboBox cmbVrstaPosla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUcinakRadnika;
    private javax.swing.JTextField txtBrojSati;
    private javax.swing.JTextField txtDatum;
    // End of variables declaration//GEN-END:variables

    private void popuniComboVrstePoslova() {
        
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.VRATI_SVE_VRSTE_POSLOVA, null);
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        
        if (so != null && so.getOdgovor() != null) {
            
            ArrayList<VrstaPosla> lista = (ArrayList<VrstaPosla>) so.getOdgovor();
            cmbVrstaPosla.removeAllItems();
            
            for (VrstaPosla vp : lista) {
                cmbVrstaPosla.addItem(vp);
            }
            
        }
        
    }

    private void popuniComboRadnika() {
        
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.VRATI_SVE_RADNIKE, null);
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        
        if (so != null && so.getOdgovor() != null) {
            ArrayList<Radnik> lista = (ArrayList<Radnik>) so.getOdgovor();
            cmbRadnik.removeAllItems();
            
            for (Radnik r : lista) {
                cmbRadnik.addItem(r);
            }
        }
        
    }

    private void srediTabelu() {
        ModelTabeleKlijent mtk = new ModelTabeleKlijent();
        tblUcinakRadnika.setModel(mtk);
    }
}
