/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.SwingUtilities;
import modeli.ModelTabeleServer;
import niti.NitSat;
import niti.OsveziNit;
import niti.PokreniServer;
import pomoc.TabelaKlasa;

/**
 *
 * @author USER
 */
public class ServerskaForma extends javax.swing.JFrame {
    
    private PokreniServer ps;

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        
        srediPocetnuFormu();
        srediTabelu();
        
        
        // obavezno setujte model tabele pre OsveziNit !!!!!!!!!!

        OsveziNit on = new OsveziNit(this);
        on.start();
        setTitle("Serverska forma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPokernut = new javax.swing.JLabel();
        btnPokreniServer = new javax.swing.JButton();
        lblSat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPokernut.setText("jLabel1");

        btnPokreniServer.setText("Pokreni server");
        btnPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniServerActionPerformed(evt);
            }
        });

        lblSat.setText("jLabel2");

        tblServer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblServer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(lblPokernut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPokernut)
                    .addComponent(btnPokreniServer))
                .addGap(21, 21, 21)
                .addComponent(lblSat)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniServerActionPerformed
        // TODO add your handling code here:
        
        
        if (ps != null && ps.isAlive()) {
            lblPokernut.setText("Server je vec pokrenut");
            return;
        }
        ps = new PokreniServer(this);
        if (ps.pokreniAkoMoze()) {
            serverPokrenutUI();
            btnPokreniServer.setEnabled(false);
        } else {
            portZauzetUI();
            ps = null; // important: failed start
        }
        
        
    }//GEN-LAST:event_btnPokreniServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
                // PokreniServer ps = new PokreniServer();
                // ps.start();
            }
        });
    }

    public void izvrsiUpit() {

        SwingUtilities.invokeLater(() -> {
            ArrayList<TabelaKlasa> noviRed = new ArrayList<>();
            for (int i = 0; i < ModelTabeleServer.BROJ_KOLONA; i++) {
                int vrednost = (int) (Math.random() * 30) + 1; // 1..30
                noviRed.add(new TabelaKlasa(i, vrednost));
            }
            ModelTabeleServer mt = (ModelTabeleServer) tblServer.getModel();
            mt.postaviRed(noviRed);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniServer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPokernut;
    private javax.swing.JLabel lblSat;
    private javax.swing.JTable tblServer;
    // End of variables declaration//GEN-END:variables

    private void srediPocetnuFormu() {
        lblPokernut.setText("Server nije pokrenut");
        jScrollPane1.setVisible(false);
        lblSat.setVisible(false);
        
        
    }
    
    private void serverPokrenutUI() {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        lblPokernut.setText("Server pokrenut  " + sdf.format(new Date()));
        jScrollPane1.setVisible(true);
        lblSat.setVisible(true);
        NitSat ns = new NitSat(lblSat);
        ns.start();
        btnPokreniServer.setVisible(false);
    }
    
    private void portZauzetUI() {
        lblPokernut.setText("Port 9000 je zauzet");
    }

    private void srediTabelu() {
        ModelTabeleServer mts = new ModelTabeleServer();
        tblServer.setModel(mts);
    }

    public String odradiPosaoKojiTreba(int pozicija, String korisnickoIme) {
        
        if (pozicija < 1 || pozicija > ModelTabeleServer.BROJ_KOLONA) {
            return "Pozicija mora biti izmedju 1 i " + ModelTabeleServer.BROJ_KOLONA;
        }
        final int kolona = pozicija - 1;
        javax.swing.SwingUtilities.invokeLater(() -> {
            ModelTabeleServer mt = (ModelTabeleServer) tblServer.getModel();
            mt.postaviVrednostUKoloni(kolona, 100);
        });
        return "Korisnik " + korisnickoIme + " je izbacio igraca sa pozicije " + pozicija;

    }
    
    
}
