/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Korisnik;

/**
 *
 * @author PC
 */
public class GlavnaForma extends javax.swing.JFrame {
    Korisnik ulogovani;

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma(Korisnik ulogovani) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Glavna forma");
        this.ulogovani = ulogovani;
        lblUlogovani.setText("Ulogovani korisnik: " + ulogovani);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiPrvaGrupa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("jLabel1");

        jMenu1.setText("Ispit");

        jmiPrvaGrupa.setText("1. Grupa");
        jmiPrvaGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrvaGrupaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPrvaGrupa);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblUlogovani)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPrvaGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrvaGrupaActionPerformed
        // TODO add your handling code here:
        UnosOsiguranja uo = new UnosOsiguranja();
        uo.pack();
        uo.setVisible(true);
        
        
    }//GEN-LAST:event_jmiPrvaGrupaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiPrvaGrupa;
    private javax.swing.JLabel lblUlogovani;
    // End of variables declaration//GEN-END:variables
}
